### ISSUE TITLE
Deleting a domain doesn't remove it from Subcomplexes

### ISSUE THREAD

**Issue by crosslinks** [crosslinks/XlinkAnalyzer#71]
1. chimera --pypath /struct/cmueller/kosinski/devel/XlinkAnalyzer/xlinkanalyzer --pypath /struct/cmueller/kosinski/devel/pyxlinks/ run.py pyt_TestPolI.py
2. Click Domains
3. Delete testdom
4. Click Subcomplexes. The testdom is there but it should not.

Maybe the delete button should open pop up saying:"
This domain is part of the following subcomplexes:
..
...
Deleting this domain will remove this domain from them.
Do you really want to delete it?

**Comment by LimpingTwerp** [comment]
Fixed.
