### ISSUE TITLE
Deleting Subcomplex doesn't work

### ISSUE THREAD

**Issue by crosslinks** [crosslinks/XlinkAnalyzer#77]
1. chimera --pypath /struct/cmueller/kosinski/devel/XlinkAnalyzer/xlinkanalyzer --pypath /struct/cmueller/kosinski/devel/pyxlinks/ run.py pyt_TestPolI.py
2. Click Subcomplexes button to open Subcomplexes window
3. Delete the subcomplex
4. Close window
5. Click Subcomplexes button to open Subcomplexes window again
6. The subcomplex is still there

**Comment by LimpingTwerp** [comment]
deleteItem method was not implememented.
