### ISSUE TITLE
Preserve extra fields

### ISSUE THREAD

**Issue by crosslinks** [crosslinks/XlinkAnalyzer#79]
If the json file contains manually added fields, not used nor saved by Xlink Analyzer, could we preserve them on Save? Say I add a top level key:value at the Subunits level manually to the text json file. I load it to Xla, it reads the json and all fields it knows. I change sth, say rename subunits, and then I do Save. I would like Xla to remember the extra fields and add to the serialized object...

Usually the extra fields are at the top level (i.e. level of the subunits, subcomplex and data) AND in data list at the Dataitem level (i.e. other data types currently not supported by xlink analyzer)

I put example file in test_data/PolI/PolI_extra_fields.json

**Comment by LimpingTwerp** [comment]
Done!
