### ISSUE TITLE
Item.explore function doesn't work properly

### ISSUE THREAD

**Issue by crosslinks** [crosslinks/XlinkAnalyzer#95]
1. It wrongly returns 2 subcomplexes when there is only one
2. If the json project is re-open within same Xla window, explore returns 2x as many subunits, domains and subcomplexes.

This in turn results in double lists in dropdowns in Domains and Subcomplexes windows.

There is test for it:
chimera --bgopacity --pypath /struct/cmueller/kosinski/devel/XlinkAnalyzer/xlinkanalyzer --pypath /struct/cmueller/kosinski/devel/pyxlinks/ run.py pyt_TestLdTwicePolI.py

**Comment by LimpingTwerp** [comment]
Fixed.
